name: "Demo Global Config"

# Local Settings
local_settings:
  enabled: True
  catalog_name: "spark_catalog"

# Remote Settings when Local settings are disabled
remote_settings:
  secret_scope: "kvss-test-weu-dev-01"
  catalog_name: "test_dev"

# Global Settings
global:
  logging: #TODO: No logging framework
    enabled: True
  validation: #TODO: No validation framework
    enabled: True
    error_on_fail: False