name: ih-ingestion-containers

services:
  app:
    container_name: ih-ingestion-container
    build:
      context: .
      dockerfile: Dockerfile
    image: ih-ingestion
    privileged: true
    init: true
    tty: true
    volumes:
      - ../:/workspace/ih-ingestion
    ports:
      - 4042:4040
    restart: unless-stopped